import test from 'tape'
import nlp from '../_lib.js'
let here = '[ordinal-more] '
nlp.verbose(false)

let arr = [
  // ['zeresimo', '0°'],
  ['primo', '1°'],
  ['secondo', '2°'],
  ['terzo', '3°'],
  ['quarto', '4°'],
  ['quinto', '5°'],
  ['sesto', '6°'],
  ['settimo', '7°'],
  ['ottavo', '8°'],
  ['nono', '9°'],
  ['decimo', '10°'],
  ['undicesimo', '11°'],
  ['dodicesimo', '12°'],
  ['tredicesimo', '13°'],
  ['quattordicesimo', '14°'],
  ['quindicesimo', '15°'],
  ['sedicesimo', '16°'],
  ['diciassettesimo', '17°'],
  ['diciottesimo', '18°'],
  ['diciannovesimo', '19°'],
  ['ventesimo', '20°'],
  ['ventunesimo', '21°'],
  ['ventiduesimo', '22°'],
  ['ventitreesimo', '23°'],
  ['ventiquattresimo', '24°'],
  ['venticinquesimo', '25°'],
  ['ventiseiesimo', '26°'],
  ['ventisettesimo', '27°'],
  ['ventottesimo', '28°'],
  ['ventinovesimo', '29°'],
  ['trentesimo', '30°'],
  ['trentunesimo', '31°'],
  ['trentaduesimo', '32°'],
  ['trentatreesimo', '33°'],
  ['trentaquattresimo', '34°'],
  ['trentacinquesimo', '35°'],
  ['trentaseiesimo', '36°'],
  ['trentasettesimo', '37°'],
  ['trentottesimo', '38°'],
  ['trentanovesimo', '39°'],
  ['quarantesimo', '40°'],
  ['quarantunesimo', '41°'],
  ['quarantaduesimo', '42°'],
  ['quarantatreesimo', '43°'],
  ['quarantaquattresimo', '44°'],
  ['quarantacinquesimo', '45°'],
  ['quarantaseiesimo', '46°'],
  ['quarantasettesimo', '47°'],
  ['quarantottesimo', '48°'],
  ['quarantanovesimo', '49°'],
  ['cinquantesimo', '50°'],
  ['cinquantunesimo', '51°'],
  ['cinquantaduesimo', '52°'],
  ['cinquantatreesimo', '53°'],
  ['cinquantaquattresimo', '54°'],
  ['cinquantacinquesimo', '55°'],
  ['cinquantaseiesimo', '56°'],
  ['cinquantasettesimo', '57°'],
  ['cinquantottesimo', '58°'],
  ['cinquantanovesimo', '59°'],
  ['sessantesimo', '60°'],
  ['sessantunesimo', '61°'],
  ['sessantaduesimo', '62°'],
  ['sessantatreesimo', '63°'],
  ['sessantaquattresimo', '64°'],
  ['sessantacinquesimo', '65°'],
  ['sessantaseiesimo', '66°'],
  ['sessantasettesimo', '67°'],
  ['sessantottesimo', '68°'],
  ['sessantanovesimo', '69°'],
  ['settantesimo', '70°'],
  ['settantunesimo', '71°'],
  ['settantaduesimo', '72°'],
  ['settantatreesimo', '73°'],
  ['settantaquattresimo', '74°'],
  ['settantacinquesimo', '75°'],
  ['settantaseiesimo', '76°'],
  ['settantasettesimo', '77°'],
  ['settantottesimo', '78°'],
  ['settantanovesimo', '79°'],
  ['ottantesimo', '80°'],
  ['ottantunesimo', '81°'],
  ['ottantaduesimo', '82°'],
  ['ottantatreesimo', '83°'],
  ['ottantaquattresimo', '84°'],
  ['ottantacinquesimo', '85°'],
  ['ottantaseiesimo', '86°'],
  ['ottantasettesimo', '87°'],
  ['ottantottesimo', '88°'],
  ['ottantanovesimo', '89°'],
  ['novantesimo', '90°'],
  ['novantunesimo', '91°'],
  ['novantaduesimo', '92°'],
  ['novantatreesimo', '93°'],
  ['novantaquattresimo', '94°'],
  ['novantacinquesimo', '95°'],
  ['novantaseiesimo', '96°'],
  ['novantasettesimo', '97°'],
  ['novantottesimo', '98°'],
  ['novantanovesimo', '99°'],
  ['centesimo', '100°'],
  ['centounesimo', '101°'],//centunesimo
  ['centoduesimo', '102°'],
  ['centotreesimo', '103°'],//centotreesimo
  ['centoquattresimo', '104°'],
  ['centocinquesimo', '105°'],
  ['centoseiesimo', '106°'],
  ['centosettesimo', '107°'],
  ['centoottesimo', '108°'],//centottesimo
  ['centonovesimo', '109°'],
  ['centodecimo', '110°'],
  ['centoundicesimo', '111°'],
  ['centododicesimo', '112°'],
  ['centotredicesimo', '113°'],
  ['centoquattordicesimo', '114°'],
  ['centoquindicesimo', '115°'],
  ['centosedicesimo', '116°'],
  ['centodiciassettesimo', '117°'],
  ['centodiciottesimo', '118°'],
  ['centodiciannovesimo', '119°'],
  ['centoventesimo', '120°'],
  ['centotrentesimo', '130°'],
  ['centoquarantesimo', '140°'],
  ['centocinquantesimo', '150°'],
  ['centosessantesimo', '160°'],
  ['centosettantesimo', '170°'],
  ['centottantesimo', '180°'],
  ['centonovantesimo', '190°'],
  ['duecentesimo', '200°'],
  ['duecentodecimo', '210°'],
  ['trecentesimo', '300°'],
  ['quattrocentesimo', '400°'],
  ['cinquecentesimo', '500°'],
  ['seicentesimo', '600°'],
  ['settecentesimo', '700°'],
  ['ottocentesimo', '800°'],
  ['novecentesimo', '900°'],
  ['millesimo', '1000°'],
  ['milleunesimo', '1001°'],
  ['duemillesimo', '2000°'],
  ['tremillesimo', '3000°'],
  ['quattromillesimo', '4000°'],
  ['cinquemillesimo', '5000°'],
  ['seimillesimo', '6000°'],
  ['settemillesimo', '7000°'],
  ['ottomillesimo', '8000°'],
  ['novemillesimo', '9000°'],
  ['decimillesimo', '10000°'],//, diecimillesimo
  ['centomillesimo', '100000°'],
  ['milionesimo', '1000000°'],
  ['duemilionesimo', '2000000°'],
  ['decimilionesimo', '10000000°'],//, diecimilionesimo
  ['centomilionesimo', '100000000°'],
]

test('ordinal-toNum:', function (t) {
  arr.forEach(a => {
    let [str, num] = a
    let doc = nlp(str)
    let m = doc.numbers().toNumber()
    t.equal(m.text(), num, here + '[toNum] ' + str)
  })
  t.end()
})

test('ordinal-toText:', function (t) {
  arr.forEach(a => {
    let [str, num] = a
    let doc = nlp(num)
    let m = doc.numbers().toText()
    t.equal(m.text(), str, here + '[toText] ' + str)
  })
  t.end()
})
