const rb = 'Adverb'
const nn = 'Noun'
const fn = 'FemaleNoun'
const mn = 'MaleNoun'
const vb = 'Verb'
const jj = 'Adjective'
// const cond = 'ConditionalVerb'
const fut = 'FutureTense'
const inf = 'Infinitive'
const g = 'Gerund'
const ref = 'Reflexive'
const imp = 'Imperative'
const pres = 'PresentTense'
// const first = 'FirstPerson'

export default [
  null,
  {
    // one-letter suffixes
  },
  {
    // two-letter suffixes
    io: nn,
    tà: fn,
    tù: fn,
    rà: fut,
  },
  {
    // three-letter suffixes
    are: inf,
    ire: inf,
    ere: inf,
    umi: nn,
    ine: nn,
    età: nn,
    ico: jj,
    one: nn,
    oni: nn,
    ore: mn,
    ema: mn,
    eva: vb,
    arà: fut,
    erà: fut,
    irà: fut,
    rrà: fut,
    vrà: fut,
    irò: fut,
    ava: imp,
    bbe: vb,
    sce: vb,
    ono: vb,

  },
  { // four-letter suffixes
    arsi: ref,
    irsi: ref,
    ersi: ref,
    endo: g,
    ando: g,
    ante: jj,
    iere: nn,
    icci: nn,//or adj
    ezze: nn,
    ista: nn,
    tore: nn,
    zolo: nn,
    lino: nn,
    zone: nn,
    eone: nn,
    lone: nn,
    cone: nn,
    lona: nn,
    ione: fn,

    enga: vb,
    para: vb,
    ntra: vb,
    tata: vb,
    izza: vb,
    iace: vb,
    duce: vb,
    cede: pres,
    iede: pres,
    lude: pres,
    inge: vb,
    iene: vb,
    enne: vb,
    dete: vb,
    vete: vb,
    duto: vb,
    vuto: vb,
    cevo: vb,
    terò: vb,
    vrei: vb,
    sati: vb,
    iamo: vb,
    vamo: vb,
    emmo: vb,
    vano: vb,
    anno: vb,
    zato: vb,
    sero: vb,
  },
  { // five-letter suffixes
    mente: rb,
    tipie: nn,
    toria: nn,
    ucchi: nn,
    ucoli: nn,
    gioni: nn,
    celli: nn,
    celle: nn,
    astri: nn,
    archi: nn,
    arche: nn,
    acchi: nn,
    nauta: nn,
    crate: nn,
    zione: nn,
    mento: nn,
    dromo: nn,
    accio: nn,
    cetto: nn,



    tacca: vb,
    plica: vb,
    nvoca: vb,
    calda: vb,
    uarda: vb,
    corda: vb,
    ambia: vb,
    rolla: vb,
    sogna: vb,
    embra: vb,
    ndata: vb,
    sulta: vb,
    senta: vb,
    venta: vb,
    porta: vb,
    catta: vb,
    dotta: vb,
    ciuta: vb,
    rriva: vb,
    lizza: vb,
    rizza: vb,
    piace: vb,
    fende: vb,
    pende: vb,
    rende: vb,
    tende: vb,
    ponde: vb,
    sorge: vb,
    prime: vb,
    rompe: vb,
    mpare: vb,
    corre: vb,
    iasse: vb,
    cesse: imp,
    vesse: imp,
    usate: vb,
    edete: vb,
    ndete: vb,
    irete: vb,
    rrete: vb,
    otete: vb,
    guite: vb,
    siste: vb,
    mette: vb,
    crive: vb,
    muove: vb,
    derai: fut,
    herai: fut,
    nosci: vb,
    orrei: vb,
    ntati: vb,
    nosco: vb,
    pongo: vb,
    gnamo: vb,
    aremo: vb,
    dremo: vb,
    eremo: vb,
    iremo: vb,
    rremo: vb,
    vremo: vb,
    ccano: vb,
    ncano: vb,
    ndano: vb,
    rlano: vb,
    inano: vb,
    orano: vb,
    trano: vb,
    rtano: vb,
    stano: vb,
    ttano: vb,
    utano: vb,
    avano: vb,
    evano: vb,
    ivano: vb,
    ovano: vb,
    bbero: vb,
    rdato: vb,
    agato: vb,
    biato: vb,
    ciato: vb,
    viato: vb,
    llato: vb,
    amato: vb,
    gnato: vb,
    rnato: vb,
    prato: vb,
    ntato: vb,
    otato: vb,
    stato: vb,
    ovato: vb,
    scito: vb,
    ntito: vb,
    tuito: vb,
    iunto: vb,
    iesto: vb,
    visto: vb,
    enuto: vb,
    ttuto: vb,
    otevo: vb,
    ovevo: vb,
    crivo: vb,
    overò: vb,
  },
  {
    // six-letter suffixes
    andoci: g,//reflexive gerund
    endoci: g,
    endomi: g,
    icelli: nn,
    icelle: nn,
    erelli: nn,
    erelle: nn,
    grafia: nn,
    ellino: nn,
    itorio: nn,
    logico: jj,
  },
  {
    // seven-letter suffixes
    grafico: jj,
    ectomia: nn,
  }
]